### ISSUE TITLE
Allow configure some naming conventions

### ISSUE THREAD

**Issue by DOrlov77** [angular/angular-hint#71] opened 2015-03-26 18:51 UTC
I want to use ng-hint module but with some nmaing convetion modification: controller ending with -"Ctrl" (the same for directive - "Drv"). Is it possible?

**Comment by SomeKittens** [comment] 2015-05-10 04:48
Duplicate of https://github.com/angular/angular-hint/issues/62

**Closed by SomeKittens** 2015-05-10 04:48 UTC
