### ISSUE TITLE
Unexpected end of expression when using 'angular-ui-bootstrap'

### ISSUE THREAD

**Issue by stephan-hof** [angular/angular-hint#98] opened 2015-06-25 13:05 UTC
Hi,

as soon as I use https://angular-ui.github.io/bootstrap/#/datepicker the following error occurs in the console log.
```
Error: [$parse:ueoe] Unexpected end of expression: move(
```

I tracked it down to the following html code inside ui-bootstrap
```
<button type="button" class="btn btn-default btn-sm pull-left" ng-click="move(-1)" tabindex="-1">
```
Looks like the ```move(-1)``` gets incorrectly parsed by the hint.js function ```getFunctionNames```.
Instead of ```['move']``` it returns ```["move(", "1)"]```

**Comment by erwinmombay** [comment] 2015-06-25 23:41
thanks. we're working this one. 

issue related to #227

the problem is in the events module at https://github.com/angular/angular-hint/blob/master/src/modules/events.js#L14

**Comment by lukekhamilton** [comment] 2015-07-01 02:53
I am also having this issue, however I not actually using the angular-hint package and it doesn't appear to be a dependence of any of the install packages on my system? 

Can someone explain why this issue is logged under the hint package? Am I missing something here.

Thanks peeps! 
Have an amazing day!

**Comment by erwinmombay** [comment] 2015-07-01 07:15
hey @lukekhamilton. if you are using batarang, angular hint comes along for the ride as it is a dependency.

**Comment by erwinmombay** [comment] 2015-08-29 06:51
should have been fixed in https://github.com/angular/angular-hint/commit/26cfc749113a599a1e11a587091c558ee2e499b6

**Closed by erwinmombay** 2015-08-29 06:51 UTC
